apiVersion: v1
kind: Namespace
metadata:
  name: fsdsfdsd-prod
  labels:
    environment-id: env_223a4e65-a81b-4cf9-9ad4-55c093927a15
    project-id: project_36f45c78-2a10-4704-b6ea-225cd9f6adf8
    project-name: fsdsfdsd
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
