apiVersion: v1
kind: Namespace
metadata:
  name: tdfgdfg-prod
  labels:
    environment-id: env_526fff2e-fe34-49e2-8cc5-286ad6ceadf4
    project-id: project_1fa321ed-6739-4ab4-adc5-f46b96f2292a
    project-name: tdfgdfg
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
