apiVersion: v1
kind: Namespace
metadata:
  name: tdfgdfg-dev
  labels:
    environment-id: env_9145c445-5612-4e64-92ff-ca53fe1d14d3
    project-id: project_1fa321ed-6739-4ab4-adc5-f46b96f2292a
    project-name: tdfgdfg
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
